on: push

jobs:
  nfc-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32
          path: "nfc"
  intercom-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: Copy .env file
        run: mv intercom/.env.template intercom/.env
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32
          path: "intercom"
  homebridge-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: homebridge/package-lock.json
      - run: npm ci
        working-directory: homebridge
      - run: npm run build
        working-directory: homebridge
          